# Site settings
title: "BohemianHacks"
email: jeff.blecha@gmail.com
description: "Practical Engineering for Impractical Ideas"
baseurl: ""
url: ""
title_description: ""
title_image: "https://www.gravatar.com/avatar/00000000000000000000000000000000?s=500&d=mm"
github_repository: https://github.com/bohemianhacks/bohemianhacks.github.io
post_limit: 5

# Social usernames/URLs
twitter_username: BohemianHacks
github_username:  BohemianHacks
xing_link:
facebook_link:

# Footer
footer_left: "Theme made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
